#include <iostream>
#include "retweet.h"
#include "../functions/a.cpp"
#include "../functions/b.cpp"
#include "../functions/c.cpp"
#include "../functions/d.cpp"
#include "../functions/e.cpp"
#include "../functions/f.cpp"
#include "../functions/g.cpp"
#include "../functions/h.cpp"
#include "../functions/i.cpp"
#include "../functions/j.cpp"
#include "../functions/k.cpp"
#include "../functions/l.cpp"
#include "../functions/m.cpp"
#include "../functions/n.cpp"
#include "../functions/o.cpp"
#include "../functions/p.cpp"
#include "../functions/q.cpp"
#include "../functions/r.cpp"
#include "../functions/s.cpp"
#include "../functions/t.cpp"
#include "../functions/u.cpp"
#include "../functions/v.cpp"
#include "../functions/w.cpp"
#include "../functions/x.cpp"
#include "../functions/y.cpp"
#include "../functions/z.cpp"

#include "../functions/aa.cpp"
#include "../functions/bb.cpp"
#include "../functions/cc.cpp"
#include "../functions/dd.cpp"
#include "../functions/ee.cpp"
#include "../functions/ff.cpp"
#include "../functions/gg.cpp"
#include "../functions/hh.cpp"
#include "../functions/ii.cpp"
#include "../functions/jj.cpp"
#include "../functions/kk.cpp"
// #include "../functions/ll.cpp"
// #include "../functions/mm.cpp"
// #include "../functions/nn.cpp"
// #include "../functions/oo.cpp"
// #include "../functions/pp.cpp"
// #include "../functions/qq.cpp"
// #include "../functions/rr.cpp"
// #include "../functions/ss.cpp"
// #include "../functions/tt.cpp"
// #include "../functions/uu.cpp"
// #include "../functions/vv.cpp"
// #include "../functions/ww.cpp"
// #include "../functions/xx.cpp"
// #include "../functions/yy.cpp"







using namespace std;
