#define PRINTALL(a) cout<<a<<"\n";
#include "../functions/a.cpp"
#include "../functions/b.cpp"
#include "../functions/j.cpp"
#include "../functions/l.cpp"
#include "../functions_double/kk.cpp"
#include "../functions_double/ll.cpp"
#include "../functions_double/mm.cpp"
#include "../functions_double/rr.cpp"
#include "../functions_double/xx.cpp"
#include "../functions_double/uu.cpp"
#include "../functions_double/ww.cpp"
#include "../functions_double/yy.cpp"