#include <iostream>
#include "retweet.h"
#include "../functions/a.cpp"
#include "../functions/b.cpp"
#include "../functions/c.cpp"
#include "../functions/d.cpp"
#include "../functions/e.cpp"
#include "../functions/f.cpp"
#include "../functions/g.cpp"
#include "../functions/h.cpp"
#include "../functions/i.cpp"
#include "../functions/j.cpp"
#include "../functions/k.cpp"
#include "../functions/l.cpp"
#include "../functions/m.cpp"
#include "../functions/n.cpp"
#include "../functions/o.cpp"
#include "../functions/p.cpp"
#include "../functions/q.cpp"
#include "../functions/r.cpp"
#include "../functions/s.cpp"
#include "../functions/t.cpp"
#include "../functions/u.cpp"
#include "../functions/v.cpp"
#include "../functions/w.cpp"
#include "../functions/x.cpp"
#include "../functions/y.cpp"
#include "../functions/z.cpp"

// #include "../functions_double/aa.cpp"
// #include "../functions_double/bb.cpp"
// #include "../functions_double/cc.cpp"
// #include "../functions_double/dd.cpp"
// #include "../functions_double/ee.cpp"
// #include "../functions_double/ff.cpp"
// #include "../functions_double/gg.cpp"



using namespace std;
